### ISSUE TITLE
Cannot find module '../lib/rml2yarrrml.js' when running yarrml-generator

### ISSUE THREAD

**Issue by WvandenBerg** [RMLio/yarrrml-parser#106]
### Description
Running `yarrrml-generator` results in `Error: Cannot find module '../lib/rml2yarrrml.js`

### Steps
```
$ npm i -g @rmlio/yarrrml-parser
$ yarrrml-parser -V
1.2.1
$ yarrrml-generator -V
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../lib/rml2yarrrml.js'
Require stack:
- D:\Hobbyhol\Programming\yarrrml-parser\bin\generator.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (D:\Hobbyhol\Programming\yarrrml-parser\bin\generator.js:11:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'D:\\Hobbyhol\\Programming\\yarrrml-parser\\bin\\generator.js'←[39m ]
}  
```

### Environment
```
$ systeminfo
...
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
...
```
```
$ Java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by pheyvaer** [comment]
Hi @WvandenBerg 

Thanks for the issue. This should be resolved by https://github.com/RMLio/yarrrml-parser/pull/103
