### ISSUE TITLE
Error generating YARRRML template

### ISSUE THREAD

**Issue by dachafra** [RMLio/yarrrml-parser#8]
```
/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:253
    const template = store.getQuads(tm, namedNode(namespaces.rr + 'template'), null).map(a => a.object)[0].value;
                                                                                                          ^

TypeError: Cannot read property 'value' of undefined
    at getYARRRMLTemplateFromTermMap (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:253:107)
    at objectMaps.forEach.om (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:127:22)
    at Array.forEach (<anonymous>)
    at predicateObjectMaps.forEach.pom (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:113:20)
    at Array.forEach (<anonymous>)
    at triplesMaps.forEach.tm (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:81:27)
    at Array.forEach (<anonymous>)
    at convertRMLtoYAML (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/lib/rml2yarrrml.js:45:15)
    at N3Parser.parser.parse [as _callback] (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/bin/generator.js:50:9)
    at N3Parser._readInTopContext (/Users/dchaves/.nvm/versions/node/v8.11.4/lib/node_modules/@rmlio/yarrrml-parser/node_modules/n3/lib/N3Parser.js:122:19)
````
The link to the file:  
[mapping.rml.txt](https://github.com/RMLio/yarrrml-parser/files/2991260/mapping.rml.txt)

**Comment by bjdmeest** [comment]
Ah yes, your mapping file contains parenttriplemaps, and the current rml2yarrrml doesn't support that yet. We'll look into this, but I don't expect this to be a quick fix though..

**Comment by bjdmeest** [comment]
3,5 years, not too shabby! Fixed in https://github.com/RMLio/yarrrml-parser/commit/257b50ac5c81593227be2158c396fae7ee4566a9! #
